### ISSUE TITLE
Document Submission Process

### ISSUE THREAD

**Issue by frankV** [boulder-python/boulderpython.org#21]
We really need some documentation that explains the submission process. I think it could be helpful to have a background on Trello that explained what each list does but don't know how Trello handles background image placement/sizing.

**Comment by svvitale** [comment]
I worry that relying on a background image will cause issues on mobile and native app versions.  What about a perma-card at the top of each list with an overview?  Kind of like a pinned discussion in a forum.

**Comment by frankV** [comment]
I think you're right. I'm in favor of adding to our documentation and just linking to it somewhere that's highly visible vs. having permanent cards. What do you think?

**Comment by svvitale** [comment]
I completely ignored your suggestion and created Trello cards to document this process under the list "How Does this Work?".  My reason for doing so is that they can be easily embedded/syndicated to other places including the website, and it gives us a nice structure since there's quite a bit of content there.  I'll add this syndication to the website shortly.

**Comment by svvitale** [comment]
@frankV @TheDataLeek please review the text of the submission guidelines at http://boulder-python-staging.herokuapp.com/submission-process
